#!/usr/bin/env python3
"""
Script para añadir comentarios técnicos al notebook 12_finetuning_transformers.ipynb
Añade documentación técnica clara sin emoticonos para hacer el notebook self-documenting.
"""

import json
from pathlib import Path

def main():
    # Ruta al notebook
    nb_path = Path('/home/eeguskiza/DEUSTO/multi-author-analysis/notebooks/12_finetuning_transformers.ipynb')

    print(f"Cargando notebook: {nb_path}")
    with open(nb_path, 'r') as f:
        nb = json.load(f)

    print(f"Total de celdas: {len(nb['cells'])}")

    # ============================================================================
    # CELDA 2: IMPORTS
    # ============================================================================
    print("\nActualizando celda 2 (imports)...")
    nb['cells'][2]['source'] = [
        "# Imports necesarios para fine-tuning con Transformers y QLoRA\n",
        "import torch\n",
        "from pathlib import Path\n",
        "import json\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "# Metricas de clasificacion binaria\n",
        "from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report\n",
        "\n",
        "# Transformers: tokenizers, modelos y entrenamiento\n",
        "from transformers import (\n",
        "    AutoTokenizer,  # Tokenizador automatico segun arquitectura del modelo\n",
        "    AutoModelForSequenceClassification,  # Modelo de clasificacion binaria\n",
        "    TrainingArguments,  # Configuracion de hiperparametros de entrenamiento\n",
        "    Trainer,  # API de alto nivel para entrenar modelos\n",
        "    DataCollatorWithPadding,  # Padding dinamico para optimizar batches\n",
        "    BitsAndBytesConfig  # Cuantizacion 4-bit para QLoRA (reduce VRAM)\n",
        ")\n",
        "\n",
        "# PEFT (Parameter-Efficient Fine-Tuning): QLoRA\n",
        "from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training, TaskType\n",
        "\n",
        "# Datasets de HuggingFace para manejo eficiente de datos\n",
        "from datasets import Dataset\n",
        "\n",
        "from tqdm.auto import tqdm\n",
        "import warnings\n",
        "warnings.filterwarnings('ignore')\n",
        "\n",
        "# Estilo de plots\n",
        "plt.style.use('seaborn-v0_8')\n",
        "pd.set_option('display.max_colwidth', 120)\n",
        "pd.set_option('display.precision', 4)\n"
    ]

    # ============================================================================
    # CELDA 7: CONFIGURACION GLOBAL
    # ============================================================================
    print("Actualizando celda 7 (configuracion global)...")
    nb['cells'][7]['source'] = [
        "# Configuracion global del experimento de fine-tuning\n",
        "# Define hiperparametros optimizados para cada arquitectura de modelo\n",
        "\n",
        "SEED = 42\n",
        "MAX_LENGTH = 128  # Tokens maximos por par de oraciones (sent_a + sent_b)\n",
        "\n",
        "# Configuracion especifica por modelo\n",
        "# Cada modelo tiene hiperparametros adaptados a su arquitectura y tamaño\n",
        "CONFIGS = {\n",
        "    \"deberta-v3-large\": {\n",
        "        \"model_name\": \"microsoft/deberta-v3-large\",\n",
        "        \"batch_size\": 4,  # Reducido para VRAM limitada (16GB GPU)\n",
        "        \"gradient_accumulation_steps\": 4,  # Simula batch_size efectivo de 16\n",
        "        \"learning_rate\": 1e-5,  # LR bajo tipico para modelos encoder grandes\n",
        "        \"epochs\": 3,\n",
        "        \"use_qlora\": False,  # Full fine-tuning (todos los parametros)\n",
        "        \"description\": \"304M params - Full fine-tuning (encoder SOTA)\"\n",
        "    },\n",
        "    \"llama-3.1-8b\": {\n",
        "        \"model_name\": \"meta-llama/Meta-Llama-3.1-8B-Instruct\",\n",
        "        \"batch_size\": 2,  # Muy reducido para QLoRA con modelo de 8B\n",
        "        \"gradient_accumulation_steps\": 8,  # Simula batch_size efectivo de 16\n",
        "        \"learning_rate\": 2e-4,  # LR mayor para LoRA (adaptadores pequeños)\n",
        "        \"epochs\": 3,\n",
        "        \"use_qlora\": True,  # QLoRA obligatorio (4-bit quantization)\n",
        "        # Configuracion QLoRA:\n",
        "        \"lora_r\": 64,  # Rank de matrices LoRA (mayor = mas expresividad)\n",
        "        \"lora_alpha\": 128,  # Escalado de LoRA (tipicamente 2*r)\n",
        "        \"lora_dropout\": 0.1,  # Regularizacion para evitar overfitting\n",
        "        # Modulos a adaptar con LoRA (atencion + FFN para maxima expresividad)\n",
        "        \"target_modules\": [\"q_proj\", \"k_proj\", \"v_proj\", \"o_proj\", \"gate_proj\", \"up_proj\", \"down_proj\"],\n",
        "        \"description\": \"8B params - QLoRA (4-bit, decoder SOTA)\"\n",
        "    },\n",
        "}\n",
        "\n",
        "# Seleccionar modelos a entrenar (comentar los que no se quieran entrenar)\n",
        "MODELS_TO_TRAIN = [\"deberta-v3-large\", \"llama-3.1-8b\"]\n",
        "\n",
        "# Mostrar configuracion\n",
        "print(\"=\"*70)\n",
        "print(\"CONFIGURACION DEL EXPERIMENTO\")\n",
        "print(\"=\"*70)\n",
        "print(f\"\\nSEED: {SEED}\")\n",
        "print(f\"MAX_LENGTH: {MAX_LENGTH} tokens\")\n",
        "print(f\"\\nModelos a entrenar: {len(MODELS_TO_TRAIN)}\")\n",
        "for model_key in MODELS_TO_TRAIN:\n",
        "    config = CONFIGS[model_key]\n",
        "    print(f\"\\n  {model_key}:\")\n",
        "    print(f\"    {config['description']}\")\n",
        "    print(f\"    Batch size: {config['batch_size']} (effective: {config['batch_size'] * config.get('gradient_accumulation_steps', 1)})\")\n",
        "    print(f\"    Learning rate: {config['learning_rate']}\")\n",
        "    print(f\"    Epochs: {config['epochs']}\")\n",
        "    if config.get('use_qlora'):\n",
        "        print(f\"    QLoRA: r={config.get('lora_r')}, alpha={config.get('lora_alpha')}\")\n",
        "print(\"=\"*70)\n"
    ]

    # ============================================================================
    # CELDA 19: FUNCION DE ENTRENAMIENTO
    # ============================================================================
    print("Actualizando celda 19 (funcion de entrenamiento)...")
    # Esta celda es muy larga, voy a leerla del notebook original y añadir comentarios clave
    original_cell_19 = ''.join(nb['cells'][19]['source'])

    # Modificar comentarios clave en la funcion
    nb['cells'][19]['source'] = [
        "# Funcion generica para entrenar modelos con soporte para Full Fine-Tuning y QLoRA\n",
        "# Automaticamente detecta la configuracion y aplica la estrategia apropiada\n",
        "\n",
        "def train_model(\n",
        "    model_key: str,\n",
        "    train_dataset: Dataset,\n",
        "    val_dataset: Dataset,\n",
        "    output_dir: Path,\n",
        "    max_steps: int = None,\n",
        "    warmup_steps: int = None,\n",
        "    eval_steps: int = 500,\n",
        "    save_steps: int = None,\n",
        ") -> dict:\n",
        "    \"\"\"\n",
        "    Entrena un modelo y devuelve metricas.\n",
        "    \n",
        "    Args:\n",
        "        model_key: Clave en CONFIGS (e.g., \"deberta-v3-large\", \"llama-3.1-8b\")\n",
        "        train_dataset: Dataset de entrenamiento\n",
        "        val_dataset: Dataset de validacion\n",
        "        output_dir: Directorio para guardar checkpoints\n",
        "        max_steps: Si se proporciona, usa max_steps en vez de num_train_epochs\n",
        "        warmup_steps: Si se proporciona, usa warmup_steps en vez de warmup_ratio\n",
        "        eval_steps: Frecuencia de evaluacion (default: 500)\n",
        "        save_steps: Frecuencia de guardado de checkpoints (default: igual a eval_steps)\n",
        "    \n",
        "    Returns:\n",
        "        dict con metricas y configuracion del modelo\n",
        "    \"\"\"\n",
        "    # Obtener configuracion del modelo desde CONFIGS\n",
        "    config = CONFIGS[model_key]\n",
        "    model_name = config[\"model_name\"]\n",
        "    use_qlora = config.get(\"use_qlora\", False)\n",
        "    \n",
        "    if save_steps is None:\n",
        "        save_steps = eval_steps\n",
        "    \n",
        "    print(f\"\\n{'='*70}\")\n",
        "    print(f\"ENTRENANDO: {model_key}\")\n",
        "    print(f\"{'='*70}\")\n",
        "    print(f\"  Modelo base: {model_name}\")\n",
        "    print(f\"  {config['description']}\")\n",
        "    print(f\"  QLoRA: {use_qlora}\")\n",
        "    print(f\"  Batch size: {config['batch_size']} (effective: {config['batch_size'] * config.get('gradient_accumulation_steps', 1)})\")\n",
        "    print(f\"  Learning rate: {config['learning_rate']}\")\n",
        "    if max_steps:\n",
        "        print(f\"  Max steps: {max_steps}\")\n",
        "    else:\n",
        "        print(f\"  Epochs: {config['epochs']}\")\n",
        "    \n",
        "    # Limpiar VRAM antes de empezar (crucial para QLoRA)\n",
        "    torch.cuda.empty_cache()\n",
        "    \n",
        "    # PASO 1: Cargar tokenizer\n",
        "    print(\"\\n[1/6] Cargando tokenizer...\")\n",
        "    tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)\n",
        "    \n",
        "    # Manejo de pad_token para modelos decoder (Llama no tiene pad_token por defecto)\n",
        "    if tokenizer.pad_token is None:\n",
        "        if \"llama\" in model_name.lower():\n",
        "            # Crear nuevo token de padding para no confundir con eos_token\n",
        "            tokenizer.add_special_tokens({'pad_token': '<|pad|>'})\n",
        "            print(\"   Pad token creado para Llama: '<|pad|>'\")\n",
        "        else:\n",
        "            tokenizer.pad_token = tokenizer.eos_token\n",
        "            print(f\"   Pad token asignado: {tokenizer.pad_token}\")\n",
        "    \n",
        "    # PASO 2: Determinar arquitectura (encoder vs decoder)\n",
        "    is_causal = \"llama\" in model_name.lower() or \"gpt\" in model_name.lower()\n",
        "    is_llama = \"llama\" in model_name.lower()\n",
        "    print(f\"   Tipo de modelo: {'Causal (Decoder)' if is_causal else 'Encoder'}\")\n",
        "    \n",
        "    # PASO 3: Cargar modelo con o sin cuantizacion\n",
        "    print(\"\\n[2/6] Cargando modelo...\")\n",
        "    if use_qlora:\n",
        "        # Configuracion de cuantizacion 4-bit (QLoRA)\n",
        "        # Reduce VRAM de ~32GB a ~6GB para modelos de 8B parametros\n",
        "        bnb_config = BitsAndBytesConfig(\n",
        "            load_in_4bit=True,  # Cuantizacion a 4 bits\n",
        "            bnb_4bit_quant_type=\"nf4\",  # NormalFloat4 (mejor que int4 para pesos normalizados)\n",
        "            bnb_4bit_compute_dtype=torch.bfloat16,  # Compute en bf16 (precision mixta)\n",
        "            bnb_4bit_use_double_quant=True,  # Doble cuantizacion (reduce VRAM adicional)\n",
        "        )\n",
        "        \n",
        "        model = AutoModelForSequenceClassification.from_pretrained(\n",
        "            model_name,\n",
        "            num_labels=2,  # Clasificacion binaria\n",
        "            quantization_config=bnb_config,\n",
        "            device_map=\"auto\",  # Distribucion automatica en GPU(s)\n",
        "            trust_remote_code=True,\n",
        "        )\n",
        "        \n",
        "        # Redimensionar embeddings si se añadio pad_token\n",
        "        if is_llama and len(tokenizer) > model.config.vocab_size:\n",
        "            model.resize_token_embeddings(len(tokenizer))\n",
        "            print(f\"   Token embeddings redimensionados a {len(tokenizer)}\")\n",
        "        \n",
        "        # Preparar modelo para k-bit training (congela pesos base, habilita gradientes en LoRA)\n",
        "        model = prepare_model_for_kbit_training(model)\n",
        "        \n",
        "        # Configurar adaptadores LoRA\n",
        "        target_modules = config.get(\"target_modules\", [\"q_proj\", \"v_proj\"])\n",
        "        \n",
        "        lora_config = LoraConfig(\n",
        "            r=config.get(\"lora_r\", 16),  # Rank de matrices LoRA (dimension latente)\n",
        "            lora_alpha=config.get(\"lora_alpha\", 32),  # Factor de escalado (alpha/r controla magnitud)\n",
        "            lora_dropout=config.get(\"lora_dropout\", 0.05),  # Dropout en adaptadores\n",
        "            bias=\"none\",  # No entrenar biases (solo matrices LoRA)\n",
        "            task_type=TaskType.SEQ_CLS,  # Tarea de clasificacion de secuencias\n",
        "            target_modules=target_modules,  # Capas a adaptar con LoRA\n",
        "        )\n",
        "        \n",
        "        model = get_peft_model(model, lora_config)\n",
        "        print(\"\\n   Parametros entrenables con LoRA:\")\n",
        "        model.print_trainable_parameters()  # Muestra % de parametros entrenables\n",
        "        \n",
        "    else:\n",
        "        # Full fine-tuning: entrenar todos los parametros del modelo\n",
        "        model = AutoModelForSequenceClassification.from_pretrained(\n",
        "            model_name,\n",
        "            num_labels=2,\n",
        "            trust_remote_code=True,\n",
        "        )\n",
        "        \n",
        "        # Redimensionar embeddings si se añadio pad_token\n",
        "        if is_llama and len(tokenizer) > model.config.vocab_size:\n",
        "            model.resize_token_embeddings(len(tokenizer))\n",
        "            print(f\"   Token embeddings redimensionados a {len(tokenizer)}\")\n",
        "        \n",
        "        model.to(\"cuda\")\n",
        "        print(f\"   Parametros totales: {sum(p.numel() for p in model.parameters()):,}\")\n",
        "        print(f\"   Parametros entrenables: {sum(p.numel() for p in model.parameters() if p.requires_grad):,}\")\n",
        "    \n",
        "    # Configurar pad_token_id en el modelo\n",
        "    if model.config.pad_token_id is None:\n",
        "        model.config.pad_token_id = tokenizer.pad_token_id\n",
        "    \n",
        "    # PASO 4: Tokenizar datasets\n",
        "    print(\"\\n[3/6] Tokenizando datasets...\")\n",
        "    # Usar prompt instructivo para modelos decoder (Llama)\n",
        "    use_instructive = is_llama\n",
        "    tokenize_fn = (get_tokenize_function_causal(tokenizer, use_instructive_prompt=use_instructive) \n",
        "                   if is_causal \n",
        "                   else get_tokenize_function(tokenizer))\n",
        "    \n",
        "    if use_instructive:\n",
        "        print(\"   Usando prompt instructivo para analisis de estilo\")\n",
        "    \n",
        "    train_tokenized = train_dataset.map(\n",
        "        tokenize_fn, \n",
        "        batched=True, \n",
        "        remove_columns=['text_a', 'text_b'],  # Mantener level y doc_id para analisis\n",
        "        desc=\"Tokenizando train\"\n",
        "    )\n",
        "    val_tokenized = val_dataset.map(\n",
        "        tokenize_fn, \n",
        "        batched=True, \n",
        "        remove_columns=['text_a', 'text_b'],\n",
        "        desc=\"Tokenizando val\"\n",
        "    )\n",
        "    \n",
        "    print(f\"   Train tokenizado: {len(train_tokenized):,} ejemplos\")\n",
        "    print(f\"   Val tokenizado: {len(val_tokenized):,} ejemplos\")\n",
        "    \n",
        "    # PASO 5: Data collator para padding dinamico (optimiza VRAM)\n",
        "    data_collator = DataCollatorWithPadding(tokenizer=tokenizer)\n",
        "    \n",
        "    # PASO 6: TrainingArguments\n",
        "    print(\"\\n[4/6] Configurando entrenamiento...\")\n",
        "    gradient_accumulation_steps = config.get('gradient_accumulation_steps', 1)\n",
        "    \n",
        "    # Calcular steps totales si se usa num_train_epochs\n",
        "    if not max_steps:\n",
        "        total_train_steps = (len(train_tokenized) // (config['batch_size'] * gradient_accumulation_steps)) * config['epochs']\n",
        "    else:\n",
        "        total_train_steps = max_steps\n",
        "    \n",
        "    # Configurar warmup (learning rate scheduling)\n",
        "    if warmup_steps is not None:\n",
        "        warmup_config = {\"warmup_steps\": warmup_steps}  # Warmup absoluto en steps\n",
        "        print(f\"   Warmup steps: {warmup_steps}\")\n",
        "    else:\n",
        "        warmup_config = {\"warmup_ratio\": 0.1}  # Warmup como % del entrenamiento\n",
        "        print(f\"   Warmup ratio: 0.1\")\n",
        "\n",
        "    training_args = TrainingArguments(\n",
        "        output_dir=str(output_dir / model_key),\n",
        "        max_steps=max_steps if max_steps else -1,  # -1 = usar num_train_epochs\n",
        "        num_train_epochs=config['epochs'] if not max_steps else 1,\n",
        "        per_device_train_batch_size=config['batch_size'],  # Batch size por GPU\n",
        "        per_device_eval_batch_size=config['batch_size'] * 2,  # Mayor batch en eval (no backprop)\n",
        "        gradient_accumulation_steps=gradient_accumulation_steps,  # Acumular gradientes para simular batch mayor\n",
        "        learning_rate=config['learning_rate'],\n",
        "        weight_decay=0.01,  # Regularizacion L2\n",
        "        eval_strategy=\"steps\",  # Evaluar cada N steps\n",
        "        eval_steps=eval_steps,\n",
        "        save_strategy=\"steps\",\n",
        "        save_steps=save_steps,\n",
        "        load_best_model_at_end=True,  # Cargar mejor checkpoint al final\n",
        "        metric_for_best_model=\"f1_macro\",  # Metrica para early stopping\n",
        "        greater_is_better=True,\n",
        "        logging_steps=100,\n",
        "        **warmup_config,\n",
        "        fp16=not use_qlora,  # FP16 para full fine-tuning\n",
        "        bf16=use_qlora,  # BF16 para QLoRA (compatible con 4-bit)\n",
        "        report_to=\"none\",  # Desactivar wandb/tensorboard\n",
        "        seed=SEED,\n",
        "        save_total_limit=2,  # Mantener solo 2 checkpoints (ahorra espacio)\n",
        "    )\n",
        "    \n",
        "    print(f\"   Gradient accumulation steps: {gradient_accumulation_steps}\")\n",
        "    print(f\"   Effective batch size: {config['batch_size'] * gradient_accumulation_steps}\")\n",
        "    print(f\"   Evaluation strategy: steps (every {eval_steps} steps)\")\n",
        "    print(f\"   Save strategy: steps (every {save_steps} steps)\")\n",
        "    print(f\"   Total training steps: {total_train_steps}, Evaluations: ~{total_train_steps // eval_steps}\")\n",
        "    \n",
        "    # PASO 7: Crear Trainer\n",
        "    trainer = Trainer(\n",
        "        model=model,\n",
        "        args=training_args,\n",
        "        train_dataset=train_tokenized,\n",
        "        eval_dataset=val_tokenized,\n",
        "        tokenizer=tokenizer,\n",
        "        data_collator=data_collator,\n",
        "        compute_metrics=compute_metrics,\n",
        "    )\n",
        "    \n",
        "    # PASO 8: Entrenar\n",
        "    print(\"\\n[5/6] Iniciando entrenamiento...\")\n",
        "    print(f\"   Total de pasos de optimizacion: {total_train_steps}\")\n",
        "    print(\"=\"*70)\n",
        "    \n",
        "    train_result = trainer.train()\n",
        "    \n",
        "    # PASO 9: Evaluar\n",
        "    print(\"\\n[6/6] Evaluando en validacion...\")\n",
        "    eval_result = trainer.evaluate()\n",
        "    \n",
        "    # PASO 10: Guardar modelo final\n",
        "    best_model_path = output_dir / model_key / \"best_model\"\n",
        "    save_final_model(trainer, model, tokenizer, best_model_path, use_qlora, model_key)\n",
        "    \n",
        "    # Limpiar VRAM para siguiente modelo\n",
        "    del model\n",
        "    del trainer\n",
        "    torch.cuda.empty_cache()\n",
        "    \n",
        "    return {\n",
        "        'model_key': model_key,\n",
        "        'train_loss': train_result.training_loss,\n",
        "        'eval_metrics': eval_result,\n",
        "        'config': config,\n",
        "    }\n",
        "\n",
        "print(\"Funcion train_model() definida.\")\n"
    ]

    # ============================================================================
    # CELDA 27: ENTRENAMIENTO LLAMA CON BALANCEO
    # ============================================================================
    print("Actualizando celda 27 (entrenamiento Llama con balanceo)...")
    nb['cells'][27]['source'] = [
        "# ============================================================================\n",
        "# Llama-3.1-8B-Instruct: QLoRA (4-bit) con Dataset Balanceado (50/50)\n",
        "# ============================================================================\n",
        "#\n",
        "# PROBLEMA DETECTADO: \"Majority Class Trap\"\n",
        "# El modelo con dataset desbalanceado (81.5% clase 0) convergia a predecir\n",
        "# siempre la clase mayoritaria, resultando en F1=0.0 para clase minoritaria.\n",
        "#\n",
        "# SOLUCION: Undersampling 50/50 para forzar discriminacion desde inicio.\n",
        "# Esto sacrifica cantidad de datos pero mejora balance y aprendizaje.\n",
        "# ============================================================================\n",
        "\n",
        "import gc\n",
        "\n",
        "MODEL_KEY = \"llama-3.1-8b\"\n",
        "\n",
        "if MODEL_KEY in MODELS_TO_TRAIN:\n",
        "    print(\"=\"*70)\n",
        "    print(\"PREPARANDO ENTRENAMIENTO CON DATASET BALANCEADO (50/50)\")\n",
        "    print(\"=\"*70)\n",
        "\n",
        "    # ========================================================================\n",
        "    # PASO 1: LIMPIEZA DE MEMORIA VRAM\n",
        "    # ========================================================================\n",
        "    print(\"\\n[1/4] Limpiando memoria VRAM...\")\n",
        "    gc.collect()  # Garbage collection de Python\n",
        "    torch.cuda.empty_cache()  # Liberar cache de CUDA\n",
        "    vram_free = (torch.cuda.get_device_properties(0).total_memory - torch.cuda.memory_allocated(0)) / 1e9\n",
        "    print(f\"   VRAM libre: {vram_free:.1f} GB\")\n",
        "\n",
        "    # ========================================================================\n",
        "    # PASO 2: BALANCEO DE DATOS (UNDERSAMPLING 50/50)\n",
        "    # ========================================================================\n",
        "    print(\"\\n[2/4] Balanceando dataset de entrenamiento (Undersampling 50/50)...\")\n",
        "\n",
        "    # Convertir Dataset a Pandas para facilitar manipulacion\n",
        "    train_df = train_dataset.to_pandas()\n",
        "\n",
        "    # Separar por clases\n",
        "    df_class_0 = train_df[train_df['label'] == 0]  # Clase mayoritaria (mismo autor)\n",
        "    df_class_1 = train_df[train_df['label'] == 1]  # Clase minoritaria (cambio)\n",
        "\n",
        "    n_class_0_original = len(df_class_0)\n",
        "    n_class_1_original = len(df_class_1)\n",
        "\n",
        "    print(f\"\\n   Dataset original (desbalanceado):\")\n",
        "    print(f\"      Clase 0 (mismo autor): {n_class_0_original:,} ({n_class_0_original/(n_class_0_original+n_class_1_original)*100:.1f}%)\")\n",
        "    print(f\"      Clase 1 (cambio):      {n_class_1_original:,} ({n_class_1_original/(n_class_0_original+n_class_1_original)*100:.1f}%)\")\n",
        "    print(f\"      Total:                 {n_class_0_original + n_class_1_original:,}\")\n",
        "\n",
        "    # Undersampling: reducir clase mayoritaria para igualar a minoritaria (ratio 1:1)\n",
        "    df_class_0_undersampled = df_class_0.sample(n=n_class_1_original, random_state=SEED)\n",
        "\n",
        "    # Combinar ambas clases\n",
        "    train_df_balanced = pd.concat([df_class_0_undersampled, df_class_1], ignore_index=True)\n",
        "\n",
        "    # Shuffle para evitar que el modelo vea ejemplos ordenados por clase\n",
        "    train_df_balanced = train_df_balanced.sample(frac=1.0, random_state=SEED).reset_index(drop=True)\n",
        "\n",
        "    # Verificar balance final\n",
        "    n_class_0_balanced = (train_df_balanced['label'] == 0).sum()\n",
        "    n_class_1_balanced = (train_df_balanced['label'] == 1).sum()\n",
        "\n",
        "    print(f\"\\n   Dataset balanceado (50/50):\")\n",
        "    print(f\"      Clase 0 (mismo autor): {n_class_0_balanced:,} ({n_class_0_balanced/(n_class_0_balanced+n_class_1_balanced)*100:.1f}%)\")\n",
        "    print(f\"      Clase 1 (cambio):      {n_class_1_balanced:,} ({n_class_1_balanced/(n_class_0_balanced+n_class_1_balanced)*100:.1f}%)\")\n",
        "    print(f\"      Total:                 {len(train_df_balanced):,}\")\n",
        "    print(f\"\\n   Reduccion: {n_class_0_original + n_class_1_original - len(train_df_balanced):,} ejemplos eliminados\")\n",
        "    print(f\"   ({(1 - len(train_df_balanced)/(n_class_0_original + n_class_1_original))*100:.1f}% reduccion)\")\n",
        "\n",
        "    # Convertir de vuelta a HuggingFace Dataset\n",
        "    train_dataset_balanced = Dataset.from_pandas(train_df_balanced, preserve_index=False)\n",
        "\n",
        "    print(f\"\\n   Columnas conservadas: {train_dataset_balanced.column_names}\")\n",
        "\n",
        "    # ========================================================================\n",
        "    # PASO 3: CREAR SUBSET DE VALIDACION\n",
        "    # ========================================================================\n",
        "    print(\"\\n[3/4] Creando subset de validacion (200 muestras)...\")\n",
        "    # Usar subset para evaluacion mas rapida durante entrenamiento\n",
        "    llama_val_subset = val_dataset.shuffle(seed=SEED).select(range(200))\n",
        "    print(f\"   Validacion: {len(llama_val_subset)} ejemplos\")\n",
        "\n",
        "    # ========================================================================\n",
        "    # PASO 4: ENTRENAR MODELO CON DATASET BALANCEADO\n",
        "    # ========================================================================\n",
        "    print(\"\\n[4/4] Entrenando Llama-3.1-8B con QLoRA en dataset balanceado...\")\n",
        "    print(f\"   max_steps: 2500 (entrenamiento por steps en vez de epochs)\")\n",
        "    print(f\"   eval_steps: 250 (validacion cada 250 pasos)\")\n",
        "    print(f\"   save_steps: 500 (checkpoint cada 500 pasos)\")\n",
        "    print(f\"   warmup_steps: 250 (10% del total de steps)\")\n",
        "    print(\"=\"*70)\n",
        "\n",
        "    results_llama = train_model(\n",
        "        MODEL_KEY,\n",
        "        train_dataset_balanced,  # Dataset balanceado 50/50\n",
        "        llama_val_subset,  # Subset de validacion (200 ejemplos)\n",
        "        CHECKPOINTS_DIR,\n",
        "        max_steps=2500,  # Entrenamiento por steps (no epochs)\n",
        "        warmup_steps=250,  # Warmup de 10%\n",
        "        eval_steps=250,  # Evaluacion frecuente para detectar problemas early\n",
        "        save_steps=500,  # Guardar checkpoints cada 500 steps\n",
        "    )\n",
        "\n",
        "    # Mostrar resultados\n",
        "    print(\"\\n\" + \"=\"*70)\n",
        "    print(\"ENTRENAMIENTO COMPLETADO - VERIFICAR F1 DE CLASE 1\")\n",
        "    print(\"=\"*70)\n",
        "    print(\"\\nSi F1 Clase 1 > 0.0, el balanceo funciono correctamente.\")\n",
        "    print(\"Si F1 Clase 1 = 0.0, el modelo sigue prediciendo solo clase 0.\\n\")\n",
        "\n",
        "    display_training_results(results_llama)\n",
        "\n",
        "    # Guardar resultados\n",
        "    all_results[MODEL_KEY] = results_llama\n",
        "\n",
        "    # Añadir metadata de balanceo para referencia futura\n",
        "    all_results[MODEL_KEY]['balancing_info'] = {\n",
        "        'strategy': 'undersampling_50_50',\n",
        "        'original_size': n_class_0_original + n_class_1_original,\n",
        "        'balanced_size': len(train_df_balanced),\n",
        "        'class_0_original': n_class_0_original,\n",
        "        'class_1_original': n_class_1_original,\n",
        "        'class_0_balanced': n_class_0_balanced,\n",
        "        'class_1_balanced': n_class_1_balanced,\n",
        "    }\n",
        "\n",
        "    save_incremental_results(all_results, REPORTS_DIR / \"12_finetuning_metrics_partial.json\")\n",
        "\n",
        "    print(f\"\\n{MODEL_KEY} completado con dataset balanceado 50/50\")\n",
        "    print(\"=\"*70)\n",
        "\n",
        "else:\n",
        "    print(f\"Saltando {MODEL_KEY} (no esta en MODELS_TO_TRAIN)\")\n"
    ]

    # ============================================================================
    # GUARDAR NOTEBOOK MODIFICADO
    # ============================================================================
    print("\nGuardando notebook modificado...")
    with open(nb_path, 'w') as f:
        json.dump(nb, f, indent=1, ensure_ascii=False)

    print(f"\nNotebook actualizado exitosamente: {nb_path}")
    print("\nCeldas modificadas:")
    print("  - Celda 2: Imports con comentarios tecnicos")
    print("  - Celda 7: Configuracion global documentada")
    print("  - Celda 19: Funcion de entrenamiento con comentarios detallados")
    print("  - Celda 27: Entrenamiento Llama con explicacion de balanceo")
    print("\nTODAS las modificaciones siguen las reglas:")
    print("  - Sin emoticonos")
    print("  - Comentarios tecnicos claros")
    print("  - Documentacion de parametros importantes")
    print("  - Explicacion de QLoRA, cuantizacion y LoRA")

if __name__ == "__main__":
    main()
